config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "pages#home"
get "/search" => "planets#search"

get "/login" => "session#new"
post "/login" => "session#create"
delete "/login" => "session#destroy"

resources :users

get "/profile" => "users#profile"


resources :regions

resources :planets

resources :moons

resources :questions do
member do
put "like", to: "questions#upvote"
put "dislike", to: "questions#downvote"
end
end

resources :replies

resources :demostrations

resources :space_station


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/demonstration.rb
class Demonstration < ApplicationRecord
  has_many :planets, through: :questions
  belongs_to :user
end

app/models/moon.rb
class Moon < ApplicationRecord
  belongs_to :planet, optional: true
  has_many :questions
  has_many :replies, through: :questions
  validates :planet_id, :name, :description,  :presence => true
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :region, optional: true
  has_many :moons
  has_many :questions
  has_many :replies, through: :questions
  validates :name, :description, :region_id, :presence => true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :planet, optional: true
  belongs_to :moon, optional: true
  belongs_to :region, optional: true
  has_many :replies
  acts_as_votable
  validates :title, :body, :presence => true
  validates :title, :length => { :minimum => 2 }
  validates :title, uniqueness: true
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :planets
  has_many :questions
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :body, :presence => true
  

end

app/models/space_station.rb
class SpaceStation < ApplicationRecord
  geocoded_by :address
  after_validation :geocode  # lookup the address and store its GPS coordinates (on create)
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  enum user_type: [:student, :specialist, :coder, :designer]
  validates :email, presence: true, uniqueness: true
  has_many :questions
  
  def has_voted_for_question?( id )
    self.votes.pluck(:question_id).include? id
  end

end

app/controllers/moons_controller.rb
class MoonsController < ApplicationController

  before_action :get_moon, only: [:show, :edit, :update, :destroy]
  before_action :check_if_logged_in, except: [:index, :show]


  def new
    @moon = Moon.new
  end

  def create
    @moon = Moon.new moon_params
    @moon.save

    if @moon.persisted?
      redirect_to moons_path

    else
      flash[:errors] = @moon.errors.full_messages
      redirect_to new_moon_path
    end
  end

  def index
    @moons = Moon.all
  end

  def show
  end

  def edit
  end

  def update
    @moon.update moon_params
    redirect_to moons_path
  end

  def destroy
    @moon.destroy
    redirect_to moons_path
  end

  private

  def moon_params
    params.require(:moon).permit(:name, :description, :image_url, :planet_id)

  end

  def get_moon
    @moon = Moon.find params[:id]
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    api_key_nasa = Rails.application.secrets.nasa_api_key
      url_nasa = "https://api.nasa.gov/planetary/apod?api_key=#{api_key_nasa}"

    results = HTTParty.get( url_nasa )
    @results = results
    # raise "hell"

    api_key_news = Rails.application.secrets.news_api_key
    url_news = "https://newsapi.org/v2/everything?q=(space AND solarsystem)&apiKey=#{api_key_news}"
    results_news = HTTParty.get( url_news )
    @results_news = results_news
    # raise "hell"
  end


end

# {
# "copyright": "Talha Zia",
# "date": "2018-05-22",
# "explanation": "Why does the right part of this image of the Moon stand out?  Shadows. The terminator line -- the line between light and dark -- occurs in the featured image so that just over half the Moon's face is illuminated by sunlight. The lunar surface appears different nearer the terminator because there the Sun is nearer the horizon and therefore causes shadows to become increasingly long.  These shadows make it easier for us to discern structure, giving us depth cues so that the two-dimensional image, when dominated by shadows, appears almost three-dimensional. Therefore, as the Moon fades from light to dark, shadows not only tell us the high from the low, but become noticeable for increasingly shorter structures. For example, many craters appear near the terminator because their height makes them easier to discern there.  The image was taken two weeks ago when the lunar phase was waning gibbous. The next full moon, a Moon without shadows, will occur one week from today.",
# "hdurl": "https://apod.nasa.gov/apod/image/1805/TerminatorMoon_Zia_1176.jpg",
# "media_type": "image",
# "service_version": "v1",
# "title": "Craters and Shadows at the Lunar Terminator",
# "url": "https://apod.nasa.gov/apod/image/1805/TerminatorMoon_Zia_960.jpg"
# }

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :check_if_logged_in, except: [:index, :show]

  before_action :check_if_owner, only: [:edit, :update, :destroy]

  before_action :get_question, only: [:show, :edit, :update, :destroy, :add_reply]


  def new
    @question = Question.new
  end

  def create
    # raise 'hell'
    @question = Question.new question_params
    @question.user = @current_user
    #save before validation
    @question.save

    if @question.persisted?
      redirect_to questions_path
    else
      flash[:errors] = @question.errors.full_messages
      redirect_to new_question_path
    end




  end

  def index
    @questions = Question.all
  end

  def show
    @reply = Reply.new
  end

  def edit
  end

  # def add_reply
  #   reply.user = @current_user
  #   @reply = Reply.new reply_params
  #
  #   reply.save
  #   redirect_to questions_path
  # end

  def update
    @question.update question_params
    redirect_to questions_path
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

# Voting

    def upvote
    @question = Question.find(params[:id])
    @question.upvote_by @current_user
    redirect_to questions_path
  end

  def downvote
    @question = Question.find(params[:id])
    @question.downvote_by @current_user
    redirect_to questions_path
  end

  private
  def question_params
    params.require(:question).permit(:title, :body, :user_id, :planet_id, :user_type, :moon_id)
  end

  def reply_params
    params.require(:reply).permit(:title, :body, :question_id)
  end
  def check_if_owner
    @question = Question.find params[:id]
    redirect_to( questions_path) and return unless @current_user.id == @question.user_id
  end

  def get_question
    @question = Question.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_if_logged_in, only: [:profile, :show ]

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params) # look in private section Doormain

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      user.image_url = req["public_id"]
    end
    #save before validation

    user.save

    if user.persisted?
      session[:user_id] = user.id
      redirect_to user_path( user.id )
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end

  end

  def show
    @user = User.find params[:id]

  end

  def profile
    @user = @current_user
    render :show

  end

  def edit
  end

  def update
    user = User.find(params[:id])
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      user.image_url = req["public_id"]
    end
    user.save
    redirect_to profile_path
  end

  def destroy
  end

  private
  # Doormain
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :user_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demonstrations_helper.rb
module DemonstrationsHelper
end

app/helpers/moons_helper.rb
module MoonsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/space_station_helper.rb
module SpaceStationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
<% if flash[:errors] %>
  <strong>The following errors need to be corrected :</strong>
  <ol>
    <% flash[:errors].each do |e| %>
    <li>
      <%= e %>
    </li>
    <% end %>
  </ol>
<% end %>
<div class="form-group row">
  <div class="col-sm-10">
  <%= f.select :planet_id, Planet.pluck(:name, :id), :include_blank => true %>
</div>
</div>
<div class="form-group row">
  <div class="col-sm-10">
  <%= f.select :moon_id, Moon.pluck(:name, :id), :include_blank => true %>
</div>
</div>
  <br>
<div class="form-group row">
  <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label(:title) %>
</label>
<div class="col-sm-10">
  <%= f.text_field(:title) %>
</div>
</div>
  <br>
<div class="form-group row">
<div class="col-sm-10">
  <%= f.text_area(:body, :size => "50x10") %>
</div>
</div>
  <br>
<div class="col-sm-10">
  <%= f.submit "Save", class: "btn btn-primary btn-lg" %>
</div>

<% end %>

app/views/questions/edit.html.erb
<h1>Questions <%= @question.title %></h1>
<%= render partial: "form" %>

app/views/questions/index.html.erb
<h1>Questions</h1>
<ul>
  <% @questions.each do |q| %>
  <li>
    <%= link_to q.title, question_path( q ) %>
  </li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<h1>Questions</h1>
<%= render partial: "form" %>

app/views/questions/show.html.erb
<h1>Question <%= @question.title %> </h1>
<%= @question.body %>

<% if @current_user.id == @question.user_id %>
<br>
<%= link_to 'Edit', edit_question_path( @question ) %>
|
<%= link_to 'Delete', question_path( @question ), method: 'delete' %>
<% end %>
<br>


<% if @question.planet.present? %>
<p>Related planet:</p>
  <%= link_to @question.planet.name, planet_path( @question.planet_id) %>
  <% else %>
<% end %>
<br>

<% if @question.moon.present? %>
<p>Related moon:</p>
  <%= link_to @question.moon.name, moon_path( @question.moon_id) %>
  <% else %>
<% end %>

<br>
<br>
<%= link_to like_question_path(@question), method: :put do %>
like
<%= @question.get_upvotes.size %>
<% end %>
||
<%= link_to dislike_question_path(@question), method: :put do %>
dislike
<%= @question.get_downvotes.size %>
<% end %>
<br>
<br>
<hr>
<p>Please type your reply below :</p>
<% if flash[:errors] %>
  <strong>The following errors need to be corrected :</strong>
  <ol>
    <% flash[:errors].each do |e| %>
    <li>
      <%= e %>
    </li>
    <% end %>
  </ol>
<% end %>
<div class="reply">
  <%= form_for @reply do |r| %>
  <div class="form-group row">
  <div class="col-sm-10">
   <%= r.text_area :body, placeholder: 'Context' %>
  </div>
  </div>
   <%= hidden_field_tag :question_id, @question.id %>
   <div class="col-sm-10">
   <%= r.submit "Save", class: "btn btn-primary btn-lg" %>
   <% end %>
</div>


<h1>Replies</h1>
<% @question.replies.each do |r| %>
  <%= r.body %> <br>
<% end %>