config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "pages#home"
get "/search" => "planets#search"

get "/login" => "session#new"
post "/login" => "session#create"
delete "/login" => "session#destroy"

resources :users

get "/profile" => "users#profile"


resources :regions

resources :planets

resources :moons

resources :questions do
member do
put "like", to: "questions#upvote"
put "dislike", to: "questions#downvote"
end
end

resources :replies

resources :demostrations

resources :space_station


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/demonstration.rb
class Demonstration < ApplicationRecord
  has_many :planets, through: :questions
  belongs_to :user
end

app/models/moon.rb
class Moon < ApplicationRecord
  belongs_to :planet, optional: true
  has_many :questions
  has_many :replies, through: :questions
  validates :planet_id, :name, :description,  :presence => true
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :region, optional: true
  has_many :moons
  has_many :questions
  has_many :replies, through: :questions
  validates :name, :description, :region_id, :presence => true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :planet, optional: true
  belongs_to :moon, optional: true
  belongs_to :region, optional: true
  has_many :replies
  acts_as_votable
  validates :title, :body, :presence => true
  validates :title, :length => { :minimum => 2 }
  validates :title, uniqueness: true
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :planets
  has_many :questions
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :body, :presence => true
  

end

app/models/space_station.rb
class SpaceStation < ApplicationRecord
  geocoded_by :address
  after_validation :geocode  # lookup the address and store its GPS coordinates (on create)
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  enum user_type: [:student, :specialist, :coder, :designer]
  validates :email, presence: true, uniqueness: true
  has_many :questions
  
  def has_voted_for_question?( id )
    self.votes.pluck(:question_id).include? id
  end

end

app/controllers/moons_controller.rb
class MoonsController < ApplicationController

  before_action :get_moon, only: [:show, :edit, :update, :destroy]
  before_action :check_if_logged_in, except: [:index, :show]


  def new
    @moon = Moon.new
  end

  def create
    @moon = Moon.new moon_params
    @moon.save

    if @moon.persisted?
      redirect_to moons_path

    else
      flash[:errors] = @moon.errors.full_messages
      redirect_to new_moon_path
    end
  end

  def index
    @moons = Moon.all
  end

  def show
  end

  def edit
  end

  def update
    @moon.update moon_params
    redirect_to moons_path
  end

  def destroy
    @moon.destroy
    redirect_to moons_path
  end

  private

  def moon_params
    params.require(:moon).permit(:name, :description, :image_url, :planet_id)

  end

  def get_moon
    @moon = Moon.find params[:id]
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    api_key_nasa = Rails.application.secrets.nasa_api_key
      url_nasa = "https://api.nasa.gov/planetary/apod?api_key=#{api_key_nasa}"

    results = HTTParty.get( url_nasa )
    @results = results
    # raise "hell"

    api_key_news = Rails.application.secrets.news_api_key
    url_news = "https://newsapi.org/v2/everything?q=(space AND solarsystem)&apiKey=#{api_key_news}"
    results_news = HTTParty.get( url_news )
    @results_news = results_news
    # raise "hell"
  end


end

# {
# "copyright": "Talha Zia",
# "date": "2018-05-22",
# "explanation": "Why does the right part of this image of the Moon stand out?  Shadows. The terminator line -- the line between light and dark -- occurs in the featured image so that just over half the Moon's face is illuminated by sunlight. The lunar surface appears different nearer the terminator because there the Sun is nearer the horizon and therefore causes shadows to become increasingly long.  These shadows make it easier for us to discern structure, giving us depth cues so that the two-dimensional image, when dominated by shadows, appears almost three-dimensional. Therefore, as the Moon fades from light to dark, shadows not only tell us the high from the low, but become noticeable for increasingly shorter structures. For example, many craters appear near the terminator because their height makes them easier to discern there.  The image was taken two weeks ago when the lunar phase was waning gibbous. The next full moon, a Moon without shadows, will occur one week from today.",
# "hdurl": "https://apod.nasa.gov/apod/image/1805/TerminatorMoon_Zia_1176.jpg",
# "media_type": "image",
# "service_version": "v1",
# "title": "Craters and Shadows at the Lunar Terminator",
# "url": "https://apod.nasa.gov/apod/image/1805/TerminatorMoon_Zia_960.jpg"
# }

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  before_action :get_planet, only: [:show, :edit, :update, :destroy]
  before_action :check_if_logged_in, except: [:index, :show]

  def search
    terms = params[:query].split(' ')
    results = Planet.where(" name LIKE? OR description LIKE?","%#{params[:query]}%", "%#{params[:query]}%")
  end

  def new
    @planet = Planet.new
  end

  def create
    planet = Planet.new planet_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      planet.image_url = req["public_id"]
    end
    planet.save

    if planet.persisted?
      redirect_to planets_path

    else
      flash[:errors] = planet.errors.full_messages
      redirect_to new_planet_path
    end

  end

  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find(params[:id])
  end

  def edit
  end

  def update
    planet = Planet.find(params[:id])
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      planet.image_url = req["public_id"]
    end
    planet.update_attributes(planet_params)
    planet.save
    redirect_to planets_path
  end

  def destroy
    @planet.destroy
    redirect_to planets_path
  end


  private

  def planet_params
    params.require(:planet).permit(:name, :description, :region_id)

  end

  def get_planet
    @planet = Planet.find params[:id]
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_if_logged_in, only: [:profile, :show ]

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params) # look in private section Doormain

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      user.image_url = req["public_id"]
    end
    #save before validation

    user.save

    if user.persisted?
      session[:user_id] = user.id
      redirect_to user_path( user.id )
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end

  end

  def show
    @user = User.find params[:id]

  end

  def profile
    @user = @current_user
    render :show

  end

  def edit
  end

  def update
    user = User.find(params[:id])
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      user.image_url = req["public_id"]
    end
    user.save
    redirect_to profile_path
  end

  def destroy
  end

  private
  # Doormain
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :user_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demonstrations_helper.rb
module DemonstrationsHelper
end

app/helpers/moons_helper.rb
module MoonsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/space_station_helper.rb
module SpaceStationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/moons/_form.html.erb
<%= form_for @moon do |f| %>
<% if flash[:errors] %>
  <strong>The following errors need to be corrected :</strong>
  <ol>
    <% flash[:errors].each do |e| %>
    <li>
      <%= e %>
    </li>
    <% end %>
  </ol>
<% end %>
<div class="form-group row">
  <div class="col-sm-10">
  <%= f.select :planet_id, Planet.pluck(:name, :id)%>
  </div>
</div>
<div class="form-group row">
  <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :name %>
</label>
<div class="col-sm-10">
  <%= f.text_field :name %>
  </div>
  </div>
  <br>

  <br>
  <div class="form-group row">
    <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :description %>
</label>
<div class="col-sm-10">
  <%= f.text_field :description %>
</div>
</div>
  <br>
  <div class="form-group row">
    <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :image_url %>
</label>
<div class="col-sm-10">
  <%= f.text_field :image_url %>
  </div>
  </div>
  <br>
  <div class="form-group row">
    <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :surface_area %>
</label>
<div class="col-sm-10">
  <%= f.text_field :surface_area %>
</div>
</div>
  <br>
  <div class="form-group row">
    <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :surface_gravity %>
</label>
<div class="col-sm-10">
  <%= f.text_field :surface_gravity %>
</div>
</div>
  <%= f.submit "Save", class: "btn btn-primary btn-lg" %>
  <% end %>

app/views/moons/edit.html.erb
<h1>Edit moon <%= @moon.name %></h1>
<%= render partial: "form" %>

app/views/moons/index.html.erb
<h1>Moons</h1>

<ul>
  <% @moons.each do |m| %>
  <li>
    <%= link_to m.name, moon_path( m ) %>
  </li>
  <% end %>
</ul>

<%= link_to 'Create new', new_moon_path( @moon ) %>

app/views/moons/new.html.erb
<h1>Create moon <%= @moon.name %></h1>
<%= render partial: "form" %>

app/views/moons/show.html.erb
<h1>Moon <%= @moon.name %> </h1>
<%= @moon.description %>
<br>
<br>
<% if @moon.image_url.present? %>
  <%= image_tag @moon.image_url, class: "img" %>
  <% end %>

<br>
<br>
<% if @current_user.present? %>
<%= link_to 'Edit', edit_moon_path( @moon ) %>
|
<%= link_to 'Delete', moon_path( @moon ), method: 'delete' %>
<% end %>

<br>
<p>Planets
</p>
<ul>
  <%= link_to @moon.planet.name, planet_path( @moon.planet_id ) %>
</ul>

app/views/planets/_form.html.erb
<%= form_for(@planet, :html => {:multipart => true}) do |f| %>
<% if flash[:errors] %>
  <strong>The following errors need to be corrected:</strong>
  <ol>
    <% flash[:errors].each do |e| %>
    <li>
      <%= e %>
    </li>
    <% end %>
  </ol>
<% end %>
<div class="form-group row">
  <div class="col-sm-10">
  <%= f.select :region_id, Region.pluck(:name, :id) %>
  </div>
</div>
<div class="form-group row">
  <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :name %>
</label>
  <div class="col-sm-10">
  <%= f.text_field :name %>
  </div>
</div>
  <br>

  <div class="form-group row">
    <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :description %>
</label>
    <div class="col-sm-10">
  <%= f.text_field :description %>
</div>
</div>
  <br>
  <div class="form-group row">
    <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label "Planet image: " %>
</label>
<div class="col-sm-10">
  <%= f.cl_image_upload :image_url %>
</div>
</div>
  <br>
  <div class="form-group row">
    <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :surface_area %>
</label>
<div class="col-sm-10">
  <%= f.text_field :surface_area %>
</div>
</div>
  <br><div class="form-group row">
    <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
      <%= f.label :surface_gravity %>
    </label>
    <div class="col-sm-10">
      <%= f.text_field :surface_gravity %>
    </div>
  </div>
      <br>
      <br>
  <div class="col-sm-10">
  <%= f.submit "Save", class: "btn btn-primary btn-lg" %>
  </div>

  <% end %>

app/views/planets/edit.html.erb
<h1>Edit planet <%= @planet.name %></h1>
<%= render partial: "form" %>

app/views/planets/index.html.erb
<h1>Planets</h1>

<ul>
  <% @planets.each do |p| %>
  <li>
    <%= link_to p.name, planet_path( p ) %>
  </li>
  <% end %>
</ul>

<%= link_to 'Create new', new_planet_path( @planet ) %>

app/views/planets/new.html.erb
<h1>Add new planet</h1>
<%= render partial: "form" %>

app/views/planets/serch.html.erb
<h1>
  Search Results for "<%= params[:query] %>"
</h1>
<hr>

<ul>
<% @results.each do |planet| %>
  <li>
    <%= link_to planet.name, planet %><br>
    <%= planet.bio %>
  </li>
<% end %>
</ul>

app/views/planets/show.html.erb
<h1>Planet <%= @planet.name %> </h1>
<%= @planet.description %>

<br>
<% if @current_user.present? %>
<%= link_to 'Edit', edit_planet_path( @planet ) %>
|
<%= link_to 'Delete', planet_path( @planet ), method: 'delete' %>
<br>
<br>
<% if @planet.questions.present? %>
<p>Related questions:</p>
<ul>
  <% @planet.questions.each do |q| %>
  <li>
    <%= link_to q.title, question_path( q ) %>
  </li>
  <% end %>
</ul>
<% else %>
<% end %>
<% end %>

<br>
<br>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/97/three.min.js"></script>
<script>
var renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth/2, window.innerHeight/2 );
document.body.appendChild( renderer.domElement );

var onRenderFcts= [];
var scene	= new THREE.Scene();
var camera	= new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.01, 1000 );
camera.position.z = 1.5;

var light	= new THREE.AmbientLight( 0xAAAAAA )
scene.add( light )
// var light	= new THREE.DirectionalLight( 'white', 1)
// light.position.set(5,5,5)
// light.target.position.set( 0, 0, 0 )
// scene.add( light )

var light	= new THREE.DirectionalLight( 0xcccccc, 1 )
light.position.set(5,3,5)
scene.add( light )

var geometry   = new THREE.SphereGeometry(0.5, 32, 32)
var material  = new THREE.MeshPhongMaterial({
  color: 0xFFFFFF,
  map:  THREE.ImageUtils.loadTexture('/assets/<%= @planet.name %>.jpg')
});
var earthMesh = new THREE.Mesh(geometry, material)
scene.add(earthMesh);

onRenderFcts.push(function(delta, now){
	earthMesh.rotateY( 1/8 * delta )
})


onRenderFcts.push(function(){
		renderer.render( scene, camera );
	})

  //////////////////////////////////////////////////////////////////////////////////
  	//		Camera Controls							//
  	//////////////////////////////////////////////////////////////////////////////////
  	var mouse	= {x : 0, y : 0}
  	document.addEventListener('mousemove', function(event){
  		mouse.x	= (event.clientX / window.innerWidth ) - 0.5
  		mouse.y	= (event.clientY / window.innerHeight) - 0.5
  	}, false)
  	onRenderFcts.push(function(delta, now){
  		camera.position.x += (mouse.x*5 - camera.position.x) * (delta*3)
  		camera.position.y += (mouse.y*5 - camera.position.y) * (delta*3)
  		camera.lookAt( scene.position )
  	})

	//////////////////////////////////////////////////////////////////////////////////
	//		loop runner							//
	//////////////////////////////////////////////////////////////////////////////////
	var lastTimeMsec= null
	requestAnimationFrame(function animate(nowMsec){
		// keep looping
		requestAnimationFrame( animate );
		// measure time
		lastTimeMsec	= lastTimeMsec || nowMsec-1000/60
		var deltaMsec	= Math.min(200, nowMsec - lastTimeMsec)
		lastTimeMsec	= nowMsec
		// call each update function
		onRenderFcts.forEach(function(onRenderFct){
			onRenderFct(deltaMsec/1000, nowMsec/1000)
		})
	});

</script>
<% if @planet.moons.present? %>
<ul>
  <p>Moons
  </p>
  <% @planet.moons.each do |m| %>
  <li>
    <%= link_to m.name, moon_path( m ) %>
  </li>
  <% end %>
</ul>
<% else %>
<% end %>



<br>
<br>

app/views/users/edit.html.erb
<h1>Users</h1>
<%= form_for(@current_user, :html => {:multipart => true}) do |f| %>
<div class="form-group row">
  <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :username %>
</label>
<div class="col-sm-10">
  <%= f.text_field :username %>
</div>
</div>
  <br>
<div class="form-group row">
  <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :email, "Email Address" %>
</label>
<div class="col-sm-10">
  <%= f.text_field :email %>
</div>
</div>
  <br>
<div class="form-group row">
<label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :image_url, "User Avatar: " %>
</label>
<div class="col-sm-10">
  <%= f.cl_image_upload :image_url, class:"img" %>
</div>
</div>
  <br>
<div class="form-group row">
<label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :password %>
</label>
<div class="col-sm-10">
  <%= f.password_field :password %>
</div>
</div>
 <br>
<div class="form-group row">
<label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :password_confirmation %>
</label>
<div class="col-sm-10">
  <%= f.password_field :password_confirmation %>
</div>
</div>
 <br>
<div class="form-group row">
<label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
 <%= f.label :user_type %>
</label>
<div class="col-sm-10">
 <%= f.select :user_type, User.user_types.keys %>
</div>
</div>
<br>
<div class="col-sm-10">
  <%= f.submit "Save", class: "btn btn-primary btn-lg"%>
</div>
<% end %>

app/views/users/new.html.erb
<h1>Create an Account</h1>

  <% if flash[:errors] %>
    <strong>Please correct the following errors :</strong>
    <ol>
      <% flash[:errors].each do |e| %>
      <li>
        <%= e %>
      </li>
      <% end %>
    </ol>
  <% end %>

  <%= form_for(@user, :html => {:multipart => true}) do |f| %>
  <div class="form-group row">
    <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
    <%= f.label :username %>
  </label>
  <div class="col-sm-10">
    <%= f.text_field :username %>
  </div>
  </div>
    <br>
  <div class="form-group row">
  <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
    <%= f.label :email, "Email Address" %>
  </label>
  <div class="col-sm-10">
    <%= f.text_field :email %>
  </div>
  </div>
    <br>
  <div class="form-group row">
  <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
    <%= f.label :image_url, "User Avatar: " %>
  </label>
  <div class="col-sm-10">
    <%= f.cl_image_upload :image_url %>
  </div>
  </div>
    <br>
  <div class="form-group row">
  <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
    <%= f.label :password %>
  </label>
  <div class="col-sm-10">
    <%= f.password_field :password %>
  </div>
  </div>
   <br>
   <div class="form-group row">
   <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
    <%= f.label :password_confirmation %>
  </label>
  <div class="col-sm-10">
    <%= f.password_field :password_confirmation %>
  </div>
  </div>
   <br>
   <div class="form-group row">
   <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
   <%= f.label :user_type %>
   </label>
   <div class="col-sm-10">
   <%= f.select :user_type, User.user_types.keys %>
   </div>
    </div>
    <br>
    <div class="col-sm-10">
    <%= f.submit "Save", class: "btn btn-primary btn-lg"%>
  </div>
  <% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>


  <% @user %>
  <%= @user.user_type %>
  <br>
  <%= cl_image_tag(@user.image_url, class: "img") %>
  <br>
  <%= link_to 'Edit', edit_user_path( @user ) %>

  <style>
  body{background: #111; margin: 0px; background-image: url('/assets/stars.png');}
  div#banner{
    width:100%;
    height:500px;
    margin: 0px auto;
    background-image: url('/assets/Earth1.png');
    background-repeat: no-repeat, repeat;
    background-position: 120%, 70px, 0px 0px;
    animation: animate-background linear 50s infinite;
  }
  @keyframes animate-background {
    from { background-position: 120% 70px, 0px 0px; }
    to { background-position: -20% 70px, 0px 0px; }

  }
  .spaceship{
    width:200px;
    height: 200px;
    margin: 200px 0px 0px 30%;
  }
  </style>
  <div id="banner">
    <img class="spaceship" src="/assets/spaceship.png" alt="">
  </div>